### ISSUE TITLE
能否给项目加个辨识度高的标题呢?

### ISSUE THREAD

**Issue by wongyah** [EstelleRao/zh-oxygenxml-userguide#2]
您好，我创建了一个叫做 [Awesome Technical Writing Learning](https://[github.com](https://github.com/wongyah/awesome-technical-writing-learning)/wongyah/awesome-technical-writing-learning) 的技术写作资源库. 我看到您这本指南之后觉得非常实用，已经将其添加到了我的资源库中（Authoring Format > DITA）。

在资源库中为这本指南添加链接时，我使用的名称是《Oxygen XML Author使用指南》，即发布成PDF文件后的封面名称。但现在有几个比较尴尬的地方：

- 这个名称很容易让人误以为是Oxygen软件的官方用户手册。
- 读者只有在发布成PDF或其他最终格式后，才能看到这本指南的名称。
- 对于不想或不会发布DITA内容的读者，要阅读这本指南的话挺不方便的。

所以，我冒昧地提几个小小的建议，您看看合不合适：

1. 将指南的名称修改一下，尽可能体现出这本指南的特点。比如，《DITA迁移和实践指南：基于Oxygen XML Author和GitLab的技术文档开发实践》、《##行业DITA迁移和实践指南……》等。
2. 在 `readme` 的开头添加一个项目标题（即这本指南的名称），让读者或存储库的访问者一眼就能知道这是什么项目。
3. 在存储库中添加一本PDF格式的指南，或者做一个展示指南内容的小网站（GitHub主页等），好让只想阅读内容的读者看得方便一些。

**Comment by EstelleRao** [comment]
1. 已更新指南名称为《DITA 结构化写作指南：基于 Oxygen XML Author 和 GitLab 的技术文档开发实践》
2. 已完善 `readme` 文件，补充项目标题
3. 考虑转为 Markdown 格式或者做成博客形式，待上线
